In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.
# Ans->Yes, there can be a difference in the data type of variables list_ and array_list.
# 1) A list in Python is a collection of items of different data types, such as strings, integers, and floats.
# 2) It is a dynamic data structure, which means that its size can change during runtime.
# 3) On the other hand, an array in Python is a collection of items of the same data type, such as integers or floats.
# 4) It is a static data structure, which means that its size is fixed during runtime.
print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


In [4]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
for i in range(len(list_)):
    print(type(list_[i]),type(array_list[i]))

<class 'str'> <class 'numpy.str_'>
<class 'str'> <class 'numpy.str_'>
<class 'str'> <class 'numpy.str_'>
<class 'str'> <class 'numpy.str_'>
<class 'str'> <class 'numpy.str_'>


In [7]:
# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.
# Ans-> Yes, there will be a change in variable array_list as its datatype is changed to int, and there will be no change in the variable list_.
for i in range(len(list_)):
    print(type(list_[i]),type(array_list[i]))

<class 'str'> <class 'numpy.int64'>
<class 'str'> <class 'numpy.int64'>
<class 'str'> <class 'numpy.int64'>
<class 'str'> <class 'numpy.int64'>
<class 'str'> <class 'numpy.int64'>


In [14]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size
print("Shape: ",num_array.shape)
print("Size: ",num_array.size)

Shape:  (2, 3)
Size:  6


In [22]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
arr = np.zeros((3,3))
print("Array:",arr)
print("Shape: ",arr.shape)
print("Size: ",arr.size)

Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape:  (3, 3)
Size:  9


In [26]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
arr1 = np.eye(5)
print(arr1)
print(arr1.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
