In [2]:
import numpy as np

In [3]:
l = [1,2,9,3,4,5,5]
a = np.array(l)
a

array([1, 2, 9, 3, 4, 5, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.asarray(l)

array([1, 2, 9, 3, 4, 5, 5])

In [7]:
np.asanyarray(l)

array([1, 2, 9, 3, 4, 5, 5])

In [8]:
b = np.matrix(l) #matrix is a two dimensional array

In [9]:
b

matrix([[1, 2, 9, 3, 4, 5, 5]])

In [10]:
c =a #it makes swallow copy , means that any changes to any of the array will change the other array too. It is just like a pointer but bidirectional

In [11]:
a

array([1, 2, 9, 3, 4, 5, 5])

In [12]:
a[0] =99
c[0]

99

In [13]:
d = np.array(a) #it will make a copy of a such that there will be no relation between them
d

array([99,  2,  9,  3,  4,  5,  5])

In [14]:
a

array([99,  2,  9,  3,  4,  5,  5])

In [15]:
a[1] = 77
d

array([99,  2,  9,  3,  4,  5,  5])

In [16]:
c

array([99, 77,  9,  3,  4,  5,  5])

In [17]:
np.fromfunction(lambda i, j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [18]:
np.fromfunction(lambda i, j : i*j , (3,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.]])

In [19]:
(i*i for i in range(5))

<generator object <genexpr> at 0x7f5fd81f47b0>

In [20]:
it =(i*i for i in range(5))

In [21]:
np.fromiter(it,int)

array([ 0,  1,  4,  9, 16])

In [22]:
np.fromstring('283 382 238',sep = ' ')

array([283., 382., 238.])

In [23]:
np.fromstring('283,382,238',sep = ',')

array([283., 382., 238.])

In [24]:
#Numpy Datatypes
l = [ 1,2,3,4,3131,31]

In [25]:
ar = np.array(l)

In [26]:
ar.ndim #states the dimension of an array

1

In [27]:
ar1 = np.array([[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]])

In [28]:
ar1

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[11, 22, 33, 44],
        [55, 66, 77, 88]]])

In [29]:
ar1.ndim

3

In [30]:
ar.shape

(6,)

In [31]:
ar1.shape # rows column and their sequence

(2, 2, 4)

In [32]:
np.arange(0.1,2.1,0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2, 1.3,
       1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [33]:
np.linspace(1,5,11) #linspace is used to generate n equal fractions from a given interval

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [34]:
np.zeros(5) #produces 1 dimensional array of size 5 and their values to zero

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((2,3)) #multidimensional array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
np.zeros((5,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [37]:
np.zeros((2,5,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [40]:
ar2 = np.ones((2,3))

In [41]:
ar2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
ar2+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [43]:
ar2*5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [44]:
np.empty((3,5)) #it is used to create an empty array with negligible values in them

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.eye(3) #it is used to create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.linspace(1,5,11) #linspace is used to generate n equal fractions from a given interval

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [47]:
np.logspace(1,5,11) #logspace is used to generate log of n equal fractions from a given interval , by default the log's base is set to 10

array([1.00000000e+01, 2.51188643e+01, 6.30957344e+01, 1.58489319e+02,
       3.98107171e+02, 1.00000000e+03, 2.51188643e+03, 6.30957344e+03,
       1.58489319e+04, 3.98107171e+04, 1.00000000e+05])

In [48]:
np.logspace(1,5,11,base=2) #logspace is used to generate log of n equal fractions from a given interval

array([ 2.        ,  2.63901582,  3.48220225,  4.59479342,  6.06286627,
        8.        , 10.55606329, 13.92880901, 18.37917368, 24.25146506,
       32.        ])

In [49]:
np.random.randn(3,4)  #it used to create matrix with randome values

array([[ 0.06642741,  0.51808757,  0.57895519,  0.44130927],
       [ 0.54283082, -1.01606642, -0.75049598,  0.091918  ],
       [ 1.256488  ,  0.36740096, -0.78986975, -0.43243657]])

In [52]:
np.random.randint(3,100,(10,10))

array([[26, 75, 86, 39, 32, 60, 39, 28, 74, 86],
       [60, 30, 68, 20, 59, 56, 23, 22, 95, 95],
       [86, 97, 32, 45, 61, 25, 63, 32,  9,  8],
       [53, 91, 35, 70,  5, 48, 67, 56, 82, 54],
       [60, 81, 70, 26, 38,  9, 61, 75, 99, 33],
       [44, 47, 23, 92, 50, 55, 94, 22, 98, 53],
       [29, 82, 56, 80, 30, 71, 13, 19, 72, 11],
       [32, 51, 18, 32, 54, 17,  8, 25, 22, 62],
       [22, 82, 73, 31, 94, 82, 29, 69, 34, 29],
       [22, 66, 51, 67, 16, 97, 59, 79, 99, 54]])

In [53]:
import pandas as pd

In [55]:
pd.DataFrame(np.random.randint(3,100,(10,10)))

0   1   2   3   4   5   6   7   8   9
0  73  70  99  59  25  61   9  95  49  78
1  74  13  92  21  34  21  44  60  65  69
2  26  33  12  85  32  55  17  43   7  93
3  77  36  56  64  79  83  82  32  36  22
4  94  81  85  45  93  72   9  86  12  17
5  81  57  97  64  82  48  20  70   7  43
6  67  93  77  94  39  66  75  28  17  39
7  36  95  11  71  38  21  14  77  31  70
8  95   6  26  17  64  86  56  66  51  85
9  21  42  63  24  71  39  54  86  47  87

In [56]:
pd.DataFrame(np.random.randint(3,100,(10,10))).to_csv('numpy_data.csv')

In [58]:
arr1=np.random.rand(3,4) 
arr1

array([[0.20569041, 0.36265444, 0.59280424, 0.80927624],
       [0.28411715, 0.14084629, 0.62095794, 0.10382635],
       [0.83981448, 0.41679578, 0.25672228, 0.11593384]])

In [60]:
arr1.reshape(6,2) #the array was 3x4 means total 12 data was there , now we can reshape it to other dim which is also equals to 12 such as 6x2

array([[0.20569041, 0.36265444],
       [0.59280424, 0.80927624],
       [0.28411715, 0.14084629],
       [0.62095794, 0.10382635],
       [0.83981448, 0.41679578],
       [0.25672228, 0.11593384]])

In [63]:
arr1.reshape(6,-13244232) # any negative value means that it will be evaluated automatically 

array([[0.20569041, 0.36265444],
       [0.59280424, 0.80927624],
       [0.28411715, 0.14084629],
       [0.62095794, 0.10382635],
       [0.83981448, 0.41679578],
       [0.25672228, 0.11593384]])

In [66]:
arr1

array([[0.20569041, 0.36265444, 0.59280424, 0.80927624],
       [0.28411715, 0.14084629, 0.62095794, 0.10382635],
       [0.83981448, 0.41679578, 0.25672228, 0.11593384]])

In [68]:
arr1[1,2]

0.6209579396272953

In [71]:
arr1[1][1:]

array([0.14084629, 0.62095794, 0.10382635])

In [79]:
arr2=np.random.randint(1,100,(4,4))

In [81]:
arr2[arr2>50]

array([93, 89, 63, 90, 89, 90, 65, 56, 84])

In [82]:
arr2

array([[93, 44, 89, 28],
       [63,  5, 90, 89],
       [90,  3, 22, 65],
       [45, 56, 84, 18]])

In [85]:
arr2[1:3,1:3]

array([[ 5, 90],
       [ 3, 22]])

In [86]:
arr2[1:3,[1,2]]

array([[ 5, 90],
       [ 3, 22]])

In [87]:
a1 = np.random.randint(1,10,(3,3))
a2 = np.random.randint(1,10,(3,3))

In [88]:
a1

array([[3, 8, 1],
       [6, 5, 1],
       [5, 1, 2]])

In [89]:
a2

array([[9, 1, 2],
       [5, 4, 5],
       [5, 6, 2]])

In [90]:
a1*a2 #multiplication by index mapping

array([[27,  8,  2],
       [30, 20,  5],
       [25,  6,  4]])

In [92]:
a1@a2 #actual matrix multiplication

array([[72, 41, 48],
       [84, 32, 39],
       [60, 21, 19]])

In [94]:
a1/0

/tmp/ipykernel_105/1504525615.py:1: RuntimeWarning: divide by zero encountered in divide
  a1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [95]:
a1+11

array([[14, 19, 12],
       [17, 16, 12],
       [16, 12, 13]])

In [96]:
a1**2

array([[ 9, 64,  1],
       [36, 25,  1],
       [25,  1,  4]])

In [97]:
#Numpy broadcasting

In [101]:
a1 = np.random.randint(1,2,(3,3))
a1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [102]:
row =np.array([1,2,3])
row

array([1, 2, 3])

In [105]:
a1 + row #it adds row wise ,broadcasting

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [108]:
a1 +row.T 

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [110]:
row.T #1d array is same as their transpose

array([1, 2, 3])

In [111]:
col = np.array([[1,2,3]])

In [112]:
col

array([[1, 2, 3]])

In [114]:
col.T #col is 2d array , it has different transpose array than the original one

array([[1],
       [2],
       [3]])

In [116]:
a1 +col.T #it adds column wise

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [118]:
np.sqrt(a1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [119]:
np.exp(a1)

array([[2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [120]:
np.log2(a1) #the value 2 can be any number

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [123]:
a2= a1.flatten() #it converts ndim to 1 dim
a1.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [125]:
np.expand_dims(a2,axis=1) #convert 1 d to 2 d vice versa

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [127]:
np.expand_dims(a2,axis=0) #convert 1 d to 2 d vice versa

array([[1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [128]:
a1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [129]:
np.squeeze(a1) 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [130]:
a2 =np.array([[1],[2],[3]])

In [131]:
a2

array([[1],
       [2],
       [3]])

In [133]:
np.squeeze(a2) 

array([1, 2, 3])

In [134]:
np.repeat(a2,4) #repeats elements of a2 4 times

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [136]:
a2

array([[1],
       [2],
       [3]])

In [139]:
np.roll(a2,2) #swap elements with given shift parameter like here is 2

array([[2],
       [3],
       [1]])

In [140]:
np.sin(a2)

array([[0.84147098],
       [0.90929743],
       [0.14112001]])

In [142]:
np.cos(a2)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ]])

In [143]:
np.tan(a2)

array([[ 1.55740772],
       [-2.18503986],
       [-0.14254654]])

In [144]:
np.sort(a2)

array([[1],
       [2],
       [3]])

In [145]:
np.count_nonzero(a1)

9

In [146]:
np.where(a1>5)

(array([], dtype=int64), array([], dtype=int64))

In [148]:
np.extract(a1<5,a1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])